name: roadstyle
channels:
  - conda-forge
dependencies:
  - python=3.11
  - geopandas
  - shapely
  - folium
  - pytest
  - pip
  - pip:
      - lonboard          # WebGL backend
      - mkdocs-material   # docs site
